language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
install:
 - echo "Y" | opam init --comp 4.02.1+BER
 - eval $(opam config env)
 - which ocamlbuild
 - metaocaml -version
 - opam --version
script:
 - ocamlbuild -ocamlc metaocamlc src/main.byte && ./main.byte
